__all__ = ["test",
           "TestBasicInformSystem",
           "TestBasicInformSystem2",
           "TestBitset",
           "TestCComputingRules",
           "TestCDiscernMatrix",
           "TestCGlobalState",
           "TestCImplArray",
           "TestCImplicant",
           "TestCInformTable",
           "TestCReduct",
           "TestCReductSet",
           "TestCRule"]